### PR TITLE
Backups

### PR DESCRIPTION
**Pull request by wonglkd**
- Backups database every hour onto the local filesystem and Dropbox
- Sends email monitoring notifications on backup health

Test plan
- Tested Dropbox uploads locally

### CODE REVIEW

**Comment by wonglkd** [comment]
TODO: DBO needs to use DBO's Dropbox account to get an app secret + OAuth token before this is merged into master.
1. Go to https://www.dropbox.com/developers/apps
2. Create app (Dropbox API, App folder, Name: LaravelBackupCUMSA)
3. Generate OAuth2 token
4. Put token + app secret inside .env file on server

TODO 2:
- Add cron job entry via cPanel `* * * * * php /path/to/artisan schedule:run >> /dev/null 2>&1` -- see https://laravel.com/docs/5.2/scheduling

**Comment by wonglkd** [comment]
@tanhanliang (cc: @tpl2go) hey Han Liang (or Ping Liang), can you use the CUMSA DBO account to get the Dropbox token please? Need your help for that - don't have access to that account. Thanks!

**Comment by tanhanliang** [comment]
The LaravelBackupCUMSA name was already taken so i created it under CUMSALaravelBackup instead. I've uploaded the file containing the token to the members-beta-repo directory.

**Comment by wonglkd** [comment]
@tanhanliang thanks! You actually need to edit the .env file in the same directory, but I've done that. Since you've created a new app, we need the app secret too (it should be a short string around 15 chars) to be inside the .env file.

**Pull request merged**
